Repository biometricITC/cPP-biometrics, pull requests merged in 2019-12, with the labels that each got.

#190 Move pad req to optional
  3_ProtectionProfile/BiocPP.adoc
  3_ProtectionProfile/PP config.adoc
  4_Methodology/BS_SD.adoc
Labels: Mobile use case

#189 Move MDFPP references to PPC
  3_ProtectionProfile/BiocPP.adoc
  3_ProtectionProfile/PP config.adoc
  3_ProtectionProfile/images/FIA_HYB_EXT.jpg
  3_ProtectionProfile/images/FIA_HYB_EXT.png
  3_ProtectionProfile/images/FIA_MBE_EXT.jpg
  3_ProtectionProfile/images/FIA_MBE_EXT.png
  3_ProtectionProfile/images/FIA_MBV_EXT.jpg
  3_ProtectionProfile/images/FIA_MBV_EXT.png
  3_ProtectionProfile/images/FPT_BDP_EXT.jpg
  3_ProtectionProfile/images/FPT_BDP_EXT.png
  3_ProtectionProfile/images/FPT_BPT_EXT.png
  3_ProtectionProfile/images/FPT_PBT_EXT.jpg
  3_ProtectionProfile/images/FPT_PBT_EXT.png
  4_Methodology/BS_SD.adoc
Labels: Mobile use case

#197 artefact definition
  3_ProtectionProfile/BiocPP.adoc
Labels: enhancement

#198 Clarification for app note
  3_ProtectionProfile/BiocPP.adoc
  3_ProtectionProfile/PP config.adoc
  4_Methodology/BS_SD.adoc
Labels: enhancement

#195 Grammar edits
  3_ProtectionProfile/BiocPP.adoc
Labels: Mobile use case, enhancement
